// MODULES //

// COMPONENTS //

// SECTIONS //

// PLUGINS //
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Pagination, Grid, Navigation, Autoplay } from "swiper/modules";

// UTILS //

// STYLES //
import styles from "@/styles/sections/digitally-svatantra/StoriesOfSuccess.module.scss";

// IMAGES //
import arrow_btn from "../../../public/img/arrow_btn.svg";
import Employees from "../../../public/img/careers/employees1.jpg";
import Qutoes from "../../../public/img/home/Qutoes.svg";

// DATA //

/** StoriesOfSuccess Component */
export default function StoriesOfSuccess() {
	return (
		<section className={`${styles.StoriesOfSuccess} pb_80`}>
			<div className="container">
				<h2 className="section_title pb_40">Stories of success</h2>
			</div>
			<div className={`${styles.slider_section}`}>
				<Swiper
					modules={[Pagination, Navigation, Grid, Autoplay]}
					// pagination={{ clickable: true }}
					spaceBetween={27}
					loop={true}
					// modules={[Navigation, Pagination, Autoplay]}
					// slidesPerView={1}
					// spaceBetween={15}
					grabCursor={true}
					speed={500}
					// loop={true}
					navigation={{
						prevEl: "#customPrev",
						nextEl: "#customNext",
					}}
					autoplay={{
						delay: 3000,
						disableOnInteraction: false,
					}}
					pagination={{
						el: ".swiper-pagination1", // Attach to a pagination container
						type: "progressbar", // Choose 'progressbar' type
						clickable: true, // Makes it interactive
					}}
					breakpoints={{
						1367: {
							slidesPerView: 1.8,
							spaceBetween: 40,
						},
						1201: {
							slidesPerView: 1.5,
							spaceBetween: 30,
						},
						1023: {
							slidesPerView: 1.3,
							spaceBetween: 25,
						},
						993: {
							slidesPerView: 1.1,
							spaceBetween: 25,
						},
						768: {
							slidesPerView: 1.3,
						},
						0: {
							spaceBetween: 12,
							slidesPerView: 1.2,
						},
					}}
					className={styles.slider}
				>
					<SwiperSlide className={`${styles.item}`}>
						<div className={`${styles.SliderItem} color_white`}>
							<img src={Qutoes.src} alt="Quote Image" />
							<p className={`${styles.quote} text_sm text_500`}>
								Laxmi’s family faces a financial challenge as the income level is on the
								lower side. With an aim to combat and overcome those challenges, Laxmi
								took her first step by availing of a loan from Chaitanya and starting a
								general store. The income generated by the store became a major source
								of income for her family over time and steadily uplifted their standard
								of living. Laxmi feels grateful for Chaitanya’s services.
							</p>
							<p className={`${styles.Name}`}>- Animol, Ambalapuzha, Kerala</p>
						</div>
					</SwiperSlide>
					<SwiperSlide className={`${styles.item}`}>
						<div className={`${styles.SliderItem} color_white`}>
							<img src={Qutoes.src} alt="Quote Image" />
							<p className={`${styles.quote} text_sm text_500`}>
								I have never missed a single EMI of my Svatantra loan and have been
								actively utilising the consumer facing app to pay by instalments.
							</p>
							<p className={`${styles.Name}`}>
								- Sakshee Sandeep Kale, Ambernath, Maharashtra
							</p>
						</div>
					</SwiperSlide>
					<SwiperSlide className={`${styles.item}`}>
						<div className={`${styles.SliderItem} color_white`}>
							<img src={Qutoes.src} alt="Quote Image" />
							<p className={`${styles.quote} text_sm text_500`}>
								It all started with a group loan to set up my kirana shop, and now I
								also own a saree shop.
							</p>
							<p className={`${styles.Name}`}>
								- Rekha Kailash Yamagavali, Amravati, Maharashtra
							</p>
						</div>
					</SwiperSlide>
					<SwiperSlide className={`${styles.item}`}>
						<div className={`${styles.SliderItem} color_white`}>
							<img src={Qutoes.src} alt="Quote Image" />
							<p className={`${styles.quote} text_sm text_500`}>
								I took a loan from Svatantra Microfin to restart my late husband’s
								transport business. Life was no doubt challenging but with hard work, we
								were able to repay the debts and start afresh.
							</p>
							<p className={`${styles.Name}`}>
								- Nanda Maruti Kokhale, Vadgaon, Pune, Maharashtra
							</p>
						</div>
					</SwiperSlide>
				</Swiper>
			</div>
			<div className="container">
				<div className={`${styles.progressBar} swiper-pagination1`}></div>
				<div className={`${styles.arrowSection} f_w_a_j_center`}>
					<button className={`${styles.customPrev}`} id="customPrev">
						<img src={arrow_btn.src} alt="icon" />
					</button>
					<button className={styles.customNext} id="customNext">
						<img src={arrow_btn.src} alt="icon" />
					</button>
				</div>
			</div>
		</section>
	);
}
